This commit fixes the following errors from the previous commit
--CMake--
install TARGETS given no LIBRARY DESTINATION for shared library target
  "utils"

install TARGETS given no LIBRARY DESTINATION for shared library target
  "names"

install TARGETS given no LIBRARY DESTINATION for shared library target
  "roll-parser"

install TARGETS given no LIBRARY DESTINATION for shared library target
  "character"

--Unix--
include/core/utils.h:37:15: error: expected ‘{’ before ‘::’ token

include/core/utils.h:37:15: error: ‘Core’ in namespace ‘::’ does not
name a type

include/core/utils.h:68:15: error: expected ‘{’ before ‘::’ token

include/core/utils.h:68:15: error: ‘Utils’ in namespace ‘::’ does not
name a type

src/utils.cpp:24:15: error: expected ‘{’ before ‘::’ token

src/utils.cpp:24:15: error: ‘Core’ in namespace ‘::’ does not name a
type

src/utils.cpp:106:15: error: expected ‘{’ before ‘::’ token

src/utils.cpp:106:15: error: ‘Utils’ in namespace ‘::’ does not name a
type

src/utils.cpp:270:1: error: expected ‘}’ at end of input

--Windows--
include\core\utils.h(37): error C2429: language feature
'nested-namespace-definition' requires compiler flag '/std:c++17'

include\core\utils.h(68): error C2429: language feature
'nested-namespace-definition' requires compiler flag '/std:c++17'

src\utils.cpp(24): error C2429: language feature
'nested-namespace-definition' requires compiler flag '/std:c++17'

src\utils.cpp(106): error C2429: language feature
'nested-namespace-definition' requires compiler flag '/std:c++17'